# Dynmap-Factions configuration
#
update:
  # Seconds between checks for Factions updates
  period: 300

layer:
  name: "Factions"
  # Make mobs layer hidden by default
  hidebydefault: false
  # ordering priority in layer menu (low goes before high - default is 0)
  layerprio: 2
  # (optional) set minimum zoom level before layer is visible (0 = defalt, always visible)
  minzoom: 0

# Format for popup - substitute values for macros
infowindow: '<div class="infowindow"><span style="font-size:160%;"><span style="font-weight:bold;">%nation%</span></span><br>%description%<br>Leader: %playerowners%<br>Members: %playermembers%</div>'

# Allow players in faction to see one another on dynmap (only relevant if dynmap has 'player-info-protected' enabled)
visibility-by-faction: true

regionstyle:
  strokeColor: "#45C96F"
  strokeOpacity: 0.8
  strokeWeight: 3
  fillColor: "#28F569"
  fillOpacity: 0.35
  homeicon: "blueflag"
  boost: false

# Optional setting to limit which regions to show, by name - if commented out, all regions are shown
# To show all regions on a given world, add 'world:<worldname>' to the list
visibleregions: [ ]

# Optional setting to hide specific regions, by name
# To hide all regions on a given world, add 'world:<worldname>' to the list
hiddenregions: [ ]

# Optional per-region overrides for regionstyle (any defined replace those in regionstyle)
custstyle:
